### PR TITLE
Updated fontconfig-sys to latest nightly

### PR DESCRIPTION
**Pull request by Victor-Savu**
- Replaced the `-` by `_` in the crate name
- Re-run **bindgen** (latest version)
- Handled var_args specifier (**bindgen** currently doesn't do that properly)
- Applied cosmetic changes to the **bindgen** output
  - removed `-> ()` return statements
  - removed preceding `::` specifications (e.g. `::std::` -> `std::`)

### CODE REVIEW

**Comment by matprec** [comment]
What's the state of this library and this PR?

**Comment by onelson** [comment]
@MSleepyPanda I was just looking at fixing up your rust-font-loader (build fails on mac).
I mentioned to jpernst that it depended on his "silverknife" binding and he said, "oh no.. don't use that!"
Was just looking for alternatives.

**Comment by matprec** [comment]
@onelson 
In first place, i would've used this library but the author seems to be absent, even building fails.
Second choice would've been servo-fontconfig, pure ffi bindings from servo, but a specific function i needed isn't correctly implement.
At the time i made rust-font-loader, i didn't had the time on hand to make the PR for it, so i went with the silverknife bindings.
You can file an issue at my repo if you want and i'll address it soon™️ 

Fore the mac part, i'd like to use coregraphics/coretex, because native. Using fontconfig on mac should work but imo it is clumsy (if you're not on linux). But since i don't own a mac/other kind of apple desktop device, i will have to wait for someone to do it.

**Comment by onelson** [comment]
I just brought home a macbook from work to try and do some testing around this. Perhaps I can help with that portion!

I also came across servo-fontconfig -- you have details about the missing feature? I can try and chase that down. It seems to be the implementation with the most activity around it, for whatever that's worth.

**Comment by matprec** [comment]
Thanks! Help is always appreciated, so feel free to submit a PR!

For the servo-fontconfig part, e.g. some [variadic function stuff](https://github.com/servo/rust-fontconfig/blob/master/src/fontconfig.rs#L379). I'll address this in the next few days, will compare it to the bindgen output.

I've open the [corresponding issues](https://github.com/MSleepyPanda/rust-font-loader/issues/3) in my repo, please discuss further questions there, as i don't want to pollute this issue, even tough unmaintained.

**Comment by Victor-Savu** [comment]
Seems like this project is abandoned :(

**Pull request closed without merging**
